### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by z3t0** [hughsk/gl-context#1]
What do the three lines at https://github.com/hughsk/gl-context/blob/master/index.js#L14
Achieve? Does it check for which returns a valid object and use that?

**Comment by hughsk** [comment]
Some older browsers required using `getContext('experimental-webgl')` to get a new WebGL context. If a context type is unsupported or unavailable, it'll return `undefined` — so this code will attempt to create a context using the first one that's supported and available :)
